name: nubank_clone
description: Nubank Clone App

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.9.0
  font_awesome_flutter: ^9.1.0
  qr_flutter: ^4.0.0
  graphql_flutter: ^5.0.0
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^3.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.1.0-alpha.1
  flutter_spinkit: ^5.0.0

dev_dependencies:
  mockito: ^5.0.11
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/nubank.png"

flutter:
  assets:
    - assets/images/
    - languages/pt_BR.json
    - languages/pt_PT.json

  uses-material-design: true

  fonts:
    - family:  NuIcons
      fonts:
        - asset: assets/fonts/NuIcons.ttf
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

